sonar.projectKey=Goodwin999_Multi-Platform-Calculator
sonar.organization=goodwin999
sonar.projectName=Multi-Platform-Calculator
sonar.projectVersion=1.0
sonar.sources=src
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8